import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider"
import AuthLoader from "@/components/AuthLoader";

// Import Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Bus Harapan Jaya",
  description: "Generated by create next app",
  icons: {
    icon: '/logo-bus.png'
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased overflow-x-hidden`}>
        <ReduxProvider>
          <AuthLoader/>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
