import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Import Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // sesuaikan dengan kebutuhan
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Bus Harapan Jaya",
  description: "Generated by create next app",
  icons: {
    icon: '/logo-bus.png' // ← Ini akan muncul di <head> sebagai favicon
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
